apiVersion: v1
kind: Service
metadata:
  name: telegram-llm-bot
  namespace: telegram-llm-bot
  labels:
    app: telegram-llm-bot
spec:
  type: NodePort
  selector:
    app: telegram-llm-bot
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30800
      protocol: TCP
      name: http
